baseURL = "https://mattische.github.io/blog/"
languageCode = "en-us"
title = "mattische/blog"

theme = "hugo-theme-pixyll" #"paperback"
publishDir = "docs"

# for theme pixyll
author = "mattische"

[indexes]
category = "categories"
tag = "tags"

[params]

# your name to display by the copyright sign
# default: undefined
AuthorName = "mattische"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "Hello, world!"

# number of posts to show on index
# default: 10
HomepagePosts = 5

# default: undefined
GithubUsername = "mattische"

# default: undefined
TwitterUsername = "mattische"

#for pixyll
twitter_username = "mattische"
paginate = true